# Generated by Django 6.0.7 on 2026-07-12 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AssetFlow', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
