# Generated by Django 6.0.7 on 2026-07-12 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetFlow', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('serial_number', models.CharField(max_length=100)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('acquisition_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('condition', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=150)),
                ('is_bookable', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ALLOCATED', 'Allocated'), ('RESERVED', 'Reserved'), ('MAINTENANCE', 'Under Maintenance'), ('LOST', 'Lost'), ('RETIRED', 'Retired'), ('DISPOSED', 'Disposed')], default='AVAILABLE', max_length=20)),
                ('expected_return_date', models.DateField(null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AssetFlow.department')),
                ('held_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_assets', to='AssetFlow.user')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AssetFlow.category')),
            ],
        ),
        migrations.CreateModel(
            name='AllocationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=25)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AssetFlow.user')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='AssetFlow.asset')),
            ],
        ),
        migrations.CreateModel(
            name='AuditCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_closed', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssetFlow.department')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssetFlow.asset')),
            ],
        ),
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(default='PENDING', max_length=10)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssetFlow.asset')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='AssetFlow.auditcycle')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(default='UPCOMING', max_length=15)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='AssetFlow.asset')),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssetFlow.user')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_description', models.TextField()),
                ('priority', models.CharField(default='MEDIUM', max_length=10)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='AssetFlow.asset')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssetFlow.user')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='AssetFlow.user')),
            ],
        ),
    ]
